# Generated by Django 2.0 on 2018-01-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20180101_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Player'),
        ),
    ]
