# Generated by Django 2.0 on 2017-12-31 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171227_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Version'),
        ),
    ]
