# Generated by Django 2.0 on 2018-01-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_player_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
