# Generated by Django 2.0 on 2018-01-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_version_submitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='teses_left',
        ),
        migrations.AddField(
            model_name='version',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Player'),
        ),
    ]
