# Generated by Django 2.0 on 2018-01-02 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20180101_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='player',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='idea',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Version'),
        ),
        migrations.AlterField(
            model_name='version',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
