# Generated by Django 2.0 on 2018-01-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20180102_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='estimated_time',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
