# Generated by Django 2.0 on 2018-01-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_idea_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.Player'),
        ),
    ]
