# Generated by Django 2.0 on 2018-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20180110_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
